### PR TITLE
Add telemetry and the first event emitted

### PR DESCRIPTION
**Pull request by oestrich**
We are interested in knowing when the enquire_link response is handled,
so add telemetry to execute an event based on this so we can hook into
it for external metrics.

Apologies for the`mix.lock` mess, looks like it hasn't been run since hex 0.20.

This is just the start and the specific event we cared about, more can be added later and should be easy to add once telemetry is in place.

### CODE REVIEW

**Comment by savonarola** [comment]
Hello! 

Thanks for the proposal.

But as far as I can see, the proposed solution volatiles the Open-closed principle. We shouldn't add orthogonal functionality to existing modules and functions.

One may do the following not to volatile the Open-closed principle. Since `SMPPEX.Session` implements `SMPPEX.TransportSession` behavior, it is possible to create a "proxy" session which
* Implements `SMPPEX.TransportSession`.
* Contains only telemetry-sending logic.
* Passes all the handling to the incapsulated `SMPPEX.Session`.

Moreover, this can be probably implemented without changing original modules at all.

**Comment by vkurup** [comment]
Hello, this PR was submitted on my behalf (@oestrich was helping me learn more about Elixir). I have implemented your suggestion in my repository (linked above) and it seems to be working. I do think it would be valuable to include something similar in your library, either as code or simply the documentation you provided above, Telemetry is a very cool piece of the elixir ecosystem (as is your library!) Thank you!

**Comment by savonarola** [comment]
Hello! Thanks, seems interesting.
I would like to try to integrate the mentioned solution, add its authors to the contributors.

**Comment by savonarola** [comment]
Added mentioned functionality in a separate library https://hexdocs.pm/smppex_telemetry/0.1.0/readme.html

**Pull request closed without merging**
